### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by sohil-vc** [CanRau/infinite-painter-brushes#1]
How to use this brushes? Any idea?

**Comment by CanRau** [comment]
Actually no, not anymore at least, not sure what I thought when I made this repo 😆 I'm sorry
I tried to copy the contents of the directories, especially custom to
`Infinite Studio/Painter/Brushes`
Yet they're not showing, even after restarting the app.

Just saw, maybe it's new 🤔, that it allows to share (export) brush folders as `.przp` file, opening them with Painter will import them.
Don't have those brushes anymore on my device tho so this repo is probably doomed 😅 

Maybe it's possible to manually recreate the brushes from the .json files and previews. I doubt it's worth the effort tho..

**Comment by sohil-vc** [comment]
Thanks for the update. Appreciate it.
